# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Askcloudhelloworld < Formula
  desc ""
  homepage "https://github.com/c3smonkey/askcloudhelloworld/"
  version "0.0.8"

  on_macos do
    url "https://github.com/c3smonkey/askcloudhelloworld/releases/download/0.0.8/askcloudhelloworld_0.0.8_darwin_all.tar.gz"
    sha256 "9a3b8b4d8139e4bc9f9aa4f6146b5f8174720fb7da029e7b8287a1e82ce16107"

    def install
      bin.install "askcloudhelloworld"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/c3smonkey/askcloudhelloworld/releases/download/0.0.8/askcloudhelloworld_0.0.8_linux_amd64.tar.gz"
        sha256 "c3a069ad94273ad6942dda79f1ace699aa4a0cae83dfd276b90c64827da5cc3e"

        def install
          bin.install "askcloudhelloworld"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/c3smonkey/askcloudhelloworld/releases/download/0.0.8/askcloudhelloworld_0.0.8_linux_arm64.tar.gz"
        sha256 "c257021f260c8b6ce1e56634d81623b54fcd54a062c07358483429650dd8710b"

        def install
          bin.install "askcloudhelloworld"
        end
      end
    end
  end
end
